
*** Constant Group: ChartPatternTypeEnum
#define chPattern5Percent                                 1
#define chPattern10Percent                                2
#define chPattern20Percent                                3
#define chPattern25Percent                                4
#define chPattern30Percent                                5
#define chPattern40Percent                                6
#define chPattern50Percent                                7
#define chPattern60Percent                                8
#define chPattern70Percent                                9
#define chPattern75Percent                                10
#define chPattern80Percent                                11
#define chPattern90Percent                                12
#define chPatternDarkHorizontal                           13
#define chPatternDarkVertical                             14
#define chPatternDarkDownwardDiagonal                     15
#define chPatternDarkUpwardDiagonal                       16
#define chPatternSmallCheckerBoard                        17
#define chPatternTrellis                                  18
#define chPatternLightHorizontal                          19
#define chPatternLightVertical                            20
#define chPatternLightDownwardDiagonal                    21
#define chPatternLightUpwardDiagonal                      22
#define chPatternSmallGrid                                23
#define chPatternDottedDiamond                            24
#define chPatternWideDownwardDiagonal                     25
#define chPatternWideUpwardDiagonal                       26
#define chPatternDashedUpwardDiagonal                     27
#define chPatternDashedDownwardDiagonal                   28
#define chPatternNarrowVertical                           29
#define chPatternNarrowHorizontal                         30
#define chPatternDashedVertical                           31
#define chPatternDashedHorizontal                         32
#define chPatternLargeConfetti                            33
#define chPatternLargeGrid                                34
#define chPatternHorizontalBrick                          35
#define chPatternLargeCheckerBoard                        36
#define chPatternSmallConfetti                            37
#define chPatternZigZag                                   38
#define chPatternSolidDiamond                             39
#define chPatternDiagonalBrick                            40
#define chPatternOutlinedDiamond                          41
#define chPatternPlaid                                    42
#define chPatternSphere                                   43
#define chPatternWeave                                    44
#define chPatternDottedGrid                               45
#define chPatternDivot                                    46
#define chPatternShingle                                  47
#define chPatternWave                                     48

*** Constant Group: ChartFillTypeEnum
#define chFillSolid                                       1
#define chFillPatterned                                   2
#define chFillGradientOneColor                            3
#define chFillGradientTwoColors                           4
#define chFillGradientPresetColors                        5
#define chFillTexturePreset                               6
#define chFillTextureUserDefined                          7

*** Constant Group: ChartPresetGradientTypeEnum
#define chGradientEarlySunset                             1
#define chGradientLateSunset                              2
#define chGradientNightfall                               3
#define chGradientDaybreak                                4
#define chGradientHorizon                                 5
#define chGradientDesert                                  6
#define chGradientOcean                                   7
#define chGradientCalmWater                               8
#define chGradientFire                                    9
#define chGradientFog                                     10
#define chGradientMoss                                    11
#define chGradientPeacock                                 12
#define chGradientWheat                                   13
#define chGradientParchment                               14
#define chGradientMahogany                                15
#define chGradientRainbow                                 16
#define chGradientRainbowII                               17
#define chGradientGold                                    18
#define chGradientGoldII                                  19
#define chGradientBrass                                   20
#define chGradientChrome                                  21
#define chGradientChromeII                                22
#define chGradientSilver                                  23
#define chGradientSapphire                                24

*** Constant Group: ChartGradientStyleEnum
#define chGradientHorizontal                              1
#define chGradientVertical                                2
#define chGradientDiagonalUp                              3
#define chGradientDiagonalDown                            4
#define chGradientFromCorner                              5
#define chGradientFromCenter                              7

*** Constant Group: ChartGradientVariantEnum
#define chGradientVariantStart                            1
#define chGradientVariantEnd                              2
#define chGradientVariantCenter                           3
#define chGradientVariantEdges                            4

*** Constant Group: ChartPresetTextureEnum
#define chTexturePapyrus                                  1
#define chTextureCanvas                                   2
#define chTextureDenim                                    3
#define chTextureWovenMat                                 4
#define chTextureWaterDroplets                            5
#define chTexturePaperBag                                 6
#define chTextureFishFossil                               7
#define chTextureSand                                     8
#define chTextureGreenMarble                              9
#define chTextureWhiteMarble                              10
#define chTextureBrownMarble                              11
#define chTextureGranite                                  12
#define chTextureNewsprint                                13
#define chTextureRecycledPaper                            14
#define chTextureParchment                                15
#define chTextureStationery                               16
#define chTextureBlueTissuePaper                          17
#define chTexturePinkTissuePaper                          18
#define chTexturePurpleMesh                               19
#define chTextureBouquet                                  20
#define chTextureCork                                     21
#define chTextureWalnut                                   22
#define chTextureOak                                      23
#define chTextureMediumWood                               24

*** Constant Group: ChartTextureFormatEnum
#define chStack                                           1
#define chStackScale                                      2
#define chStretch                                         3
#define chTile                                            4
#define chStretchPlot                                     5

*** Constant Group: ChartTexturePlacementEnum
#define chAllFaces                                        7
#define chEnd                                             2
#define chEndSides                                        6
#define chFront                                           1
#define chFrontEnd                                        3
#define chFrontSides                                      5
#define chSides                                           4
#define chProjectFront                                    8

*** Constant Group: ChartLineDashStyleEnum
#define chLineDash                                        0
#define chLineDashDot                                     1
#define chLineDashDotDot                                  2
#define chLineLongDash                                    4
#define chLineLongDashDot                                 5
#define chLineRoundDot                                    6
#define chLineSolid                                       7
#define chLineSquareDot                                   8

*** Constant Group: LineWeightEnum
#define owcLineWeightHairline                             0
#define owcLineWeightThin                                 1
#define owcLineWeightMedium                               2
#define owcLineWeightThick                                3

*** Constant Group: UnderlineStyleEnum
#define owcUnderlineStyleNone                             0
#define owcUnderlineStyleSingle                           1
#define owcUnderlineStyleDouble                           2
#define owcUnderlineStyleSingleAccounting                 3
#define owcUnderlineStyleDoubleAccounting                 4

*** Constant Group: ChartLineMiterEnum
#define chLineMiterBevel                                  0
#define chLineMiterMiter                                  1
#define chLineMiterRound                                  2

*** Constant Group: ChartDrawModesEnum
#define chDrawModePaint                                   1
#define chDrawModeSelection                               2
#define chDrawModeHitTest                                 3
#define chDrawModeScale                                   4

*** Constant Group: ChartChartLayoutEnum
#define chChartLayoutAutomatic                            0
#define chChartLayoutHorizontal                           1
#define chChartLayoutVertical                             2

*** Constant Group: ChartScaleOrientationEnum
#define chScaleOrientationMinMax                          0
#define chScaleOrientationMaxMin                          1

*** Constant Group: ChartScaleTypeEnum
#define chScaleTypeLinear                                 0
#define chScaleTypeLogarithmic                            1

*** Constant Group: ChartAxisCrossesEnum
#define chAxisCrossesAutomatic                            0
#define chAxisCrossesCustom                               3

*** Constant Group: ChartSelectionsEnum
#define chSelectionNone                                   -1
#define chSelectionAxis                                   0
#define chSelectionChart                                  1
#define chSelectionPlotArea                               2
#define chSelectionDataLabels                             3
#define chSelectionErrorbars                              4
#define chSelectionGridlines                              5
#define chSelectionLegend                                 6
#define chSelectionLegendEntry                            7
#define chSelectionPoint                                  8
#define chSelectionSeries                                 9
#define chSelectionTitle                                  10
#define chSelectionTrendline                              11
#define chSelectionChartSpace                             12
#define chSelectionSurface                                13
#define chSelectionField                                  14
#define chSelectionUserDefined                            -2
#define chSelectionCategoryLabel                          16
#define chSelectionDropZone                               17
#define chSelectionDataLabel                              18

*** Constant Group: ChartTickMarkEnum
#define chTickMarkAutomatic                               0
#define chTickMarkNone                                    1
#define chTickMarkInside                                  2
#define chTickMarkOutside                                 3
#define chTickMarkCross                                   4

*** Constant Group: ChartAxisPositionEnum
#define chAxisPositionTop                                 -1
#define chAxisPositionBottom                              -2
#define chAxisPositionLeft                                -3
#define chAxisPositionRight                               -4
#define chAxisPositionRadial                              -5
#define chAxisPositionCircular                            -6
#define chAxisPositionCategory                            -7
#define chAxisPositionTimescale                           -7
#define chAxisPositionValue                               -8
#define chAxisPositionSeries                              -9
#define chAxisPositionPrimary                             -10
#define chAxisPositionSecondary                           -11

*** Constant Group: ChartTitlePositionEnum
#define chTitlePositionAutomatic                          0
#define chTitlePositionTop                                1
#define chTitlePositionBottom                             2
#define chTitlePositionLeft                               3
#define chTitlePositionRight                              4

*** Constant Group: ChartAxisTypeEnum
#define chCategoryAxis                                    0
#define chValueAxis                                       1
#define chTimescaleAxis                                   2
#define chSeriesAxis                                      3

*** Constant Group: ChartAxisGroupingEnum
#define chAxisGroupingNone                                0
#define chAxisGroupingAuto                                1
#define chAxisGroupingManual                              2

*** Constant Group: ChartAxisUnitTypeEnum
#define chAxisUnitDay                                     0
#define chAxisUnitWeek                                    1
#define chAxisUnitMonth                                   2
#define chAxisUnitQuarter                                 3
#define chAxisUnitYear                                    4

*** Constant Group: ChartGroupingTotalFunctionEnum
#define chFunctionSum                                     1
#define chFunctionCount                                   2
#define chFunctionMin                                     3
#define chFunctionMax                                     4
#define chFunctionAvg                                     5
#define chFunctionDefault                                 6

*** Constant Group: PivotHAlignmentEnum
#define plHAlignAutomatic                                 0
#define plHAlignLeft                                      1
#define plHAlignCenter                                    2
#define plHAlignRight                                     3

*** Constant Group: PivotFieldGroupOnEnum
#define plGroupOnEachValue                                0
#define plGroupOnPrefixChars                              1
#define plGroupOnYears                                    2
#define plGroupOnQtrs                                     3
#define plGroupOnMonths                                   4
#define plGroupOnWeeks                                    5
#define plGroupOnDays                                     6
#define plGroupOnHours                                    7
#define plGroupOnMinutes                                  8
#define plGroupOnSeconds                                  9
#define plGroupOnInterval                                 10

*** Constant Group: PivotFieldSortDirectionEnum
#define plSortDirectionDefault                            0
#define plSortDirectionAscending                          1
#define plSortDirectionDescending                         2
#define plSortDirectionCustom                             4
#define plSortDirectionCustomAscending                    5
#define plSortDirectionCustomDescending                   6

*** Constant Group: PivotFieldTypeEnum
#define plTypeRegular                                     1
#define plTypeCalculated                                  2
#define plTypeTimeYears                                   4
#define plTypeTimeHalfYears                               5
#define plTypeTimeQuarters                                6
#define plTypeTimeMonths                                  7
#define plTypeTimeWeeks                                   8
#define plTypeTimeDays                                    9
#define plTypeTimeHours                                   10
#define plTypeTimeMinutes                                 11
#define plTypeTimeSeconds                                 12
#define plTypeTimeUndefined                               13
#define plTypeUnknown                                     14
#define plTypeUserDefined                                 15
#define plTypeTimeWeekdays                                16
#define plTypeCustomGroup                                 17

*** Constant Group: PivotFieldFilterFunctionEnum
#define plFilterFunctionNone                              0
#define plFilterFunctionTopCount                          3
#define plFilterFunctionBottomCount                       4
#define plFilterFunctionTopPercent                        5
#define plFilterFunctionBottomPercent                     6
#define plFilterFunctionTopSum                            7
#define plFilterFunctionBottomSum                         8

*** Constant Group: PivotTotalFunctionEnum
#define plFunctionUnknown                                 0
#define plFunctionSum                                     1
#define plFunctionCount                                   2
#define plFunctionMin                                     3
#define plFunctionMax                                     4
#define plFunctionAverage                                 5
#define plFunctionStdDev                                  6
#define plFunctionVar                                     7
#define plFunctionStdDevP                                 10
#define plFunctionVarP                                    11
#define plFunctionCalculated                              127

*** Constant Group: PivotTotalTypeEnum
#define plTotalTypeIntrinsic                              1
#define plTotalTypeUserDefined                            2
#define plTotalTypeCalculated                             3

*** Constant Group: PivotShowAsEnum
#define plShowAsNormal                                    0
#define plShowAsPercentOfRowTotal                         1
#define plShowAsPercentOfColumnTotal                      2
#define plShowAsPercentOfRowParent                        3
#define plShowAsPercentOfColumnParent                     4
#define plShowAsPercentOfGrandTotal                       5

*** Constant Group: PivotMemberPropertyDisplayEnum
#define plDisplayPropertyNone                             0
#define plDisplayPropertyInReport                         1
#define plDisplayPropertyInScreenTip                      2
#define plDisplayPropertyInAll                            3

*** Constant Group: PivotMemberFindFormatEnum
#define plFindFormatMember                                0
#define plFindFormatPathName                              1
#define plFindFormatPathInt                               2
#define plFindFormatPathHex                               3

*** Constant Group: PivotMemberCustomGroupTypeEnum
#define plGroupTypeRegular                                1
#define plGroupTypeCustomGroup                            2
#define plGroupTypeFallThrough                            3
#define plGroupTypePlaceHolder                            4
#define plGroupTypeStaticOther                            5
#define plGroupTypeDynamicOther                           6

*** Constant Group: PivotFieldSetOrientationEnum
#define plOrientationNone                                 0
#define plOrientationColumnAxis                           1
#define plOrientationRowAxis                              2
#define plOrientationFilterAxis                           4
#define plOrientationDataAxis                             8
#define plOrientationPageAxis                             16

*** Constant Group: PivotFieldSetTypeEnum
#define plFieldSetTypeTime                                1
#define plFieldSetTypeOther                               2
#define plFieldSetTypeUnknown                             3
#define plFieldSetTypeUserDefined                         4

*** Constant Group: PivotMembersCompareByEnum
#define plMembersCompareByUniqueName                      0
#define plMembersCompareByName                            1

*** Constant Group: PivotFilterUpdateMemberStateEnum
#define plMemberStateClear                                1
#define plMemberStateChecked                              2
#define plMemberStateGray                                 3

*** Constant Group: PivotFieldSetAllIncludeExcludeEnum
#define plAllDefault                                      0
#define plAllInclude                                      1
#define plAllExclude                                      2

*** Constant Group: PivotViewTotalOrientationEnum
#define plTotalOrientationRow                             1
#define plTotalOrientationColumn                          2

*** Constant Group: PivotTableExpandEnum
#define plExpandAutomatic                                 0
#define plExpandAlways                                    1
#define plExpandNever                                     2

*** Constant Group: PivotExportActionEnum
#define plExportActionNone                                0
#define plExportActionOpenInExcel                         1

*** Constant Group: ProviderType
#define providerTypeUnknown                               1
#define providerTypeRelational                            2
#define providerTypeMultidimensional                      3

*** Constant Group: PivotTableMemberExpandEnum
#define plMemberExpandAutomatic                           0
#define plMemberExpandAlways                              1
#define plMemberExpandNever                               2

*** Constant Group: PivotScrollTypeEnum
#define plScrollTypeNone                                  0
#define plScrollTypeTop                                   1
#define plScrollTypeLeft                                  2
#define plScrollTypeBottom                                4
#define plScrollTypeRight                                 8
#define plScrollTypeAll                                   15

*** Constant Group: PivotArrowModeEnum
#define plArrowModeAccept                                 0
#define plArrowModeEdit                                   1

*** Constant Group: PivotCaretPositionEnum
#define plCaretPositionAtEnd                              0
#define plCaretPositionAtMouse                            1

*** Constant Group: PivotEditModeEnum
#define plEditNone                                        0
#define plEditInProgress                                  1

*** Constant Group: ChartLegendPositionEnum
#define chLegendPositionAutomatic                         0
#define chLegendPositionTop                               1
#define chLegendPositionBottom                            2
#define chLegendPositionLeft                              3
#define chLegendPositionRight                             4

*** Constant Group: ChartProjectionModeEnum
#define chProjectionModePerspective                       0
#define chProjectionModeOrthographic                      1

*** Constant Group: ChartDataLabelPositionEnum
#define chLabelPositionAutomatic                          0
#define chLabelPositionCenter                             1
#define chLabelPositionInsideEnd                          2
#define chLabelPositionInsideBase                         3
#define chLabelPositionOutsideEnd                         4
#define chLabelPositionOutsideBase                        5
#define chLabelPositionLeft                               6
#define chLabelPositionRight                              7
#define chLabelPositionTop                                8
#define chLabelPositionBottom                             9

*** Constant Group: ChartDimensionsEnum
#define chDimSeriesNames                                  0
#define chDimCategories                                   1
#define chDimValues                                       2
#define chDimYValues                                      3
#define chDimXValues                                      4
#define chDimOpenValues                                   5
#define chDimCloseValues                                  6
#define chDimHighValues                                   7
#define chDimLowValues                                    8
#define chDimBubbleValues                                 9
#define chDimRValues                                      10
#define chDimThetaValues                                  11
#define chDimFilter                                       14
#define chDimCharts                                       15
#define chDimFormatValues                                 16

*** Constant Group: ChartEndStyleEnum
#define chEndStyleNone                                    1
#define chEndStyleCap                                     2

*** Constant Group: ChartErrorBarDirectionEnum
#define chErrorBarDirectionY                              0
#define chErrorBarDirectionX                              1

*** Constant Group: ChartErrorBarIncludeEnum
#define chErrorBarIncludePlusValues                       0
#define chErrorBarIncludeMinusValues                      1
#define chErrorBarIncludeBoth                             2

*** Constant Group: ChartErrorBarTypeEnum
#define chErrorBarTypeFixedValue                          0
#define chErrorBarTypePercent                             1
#define chErrorBarTypeCustom                              2

*** Constant Group: ChartErrorBarCustomValuesEnum
#define chErrorBarPlusValues                              12
#define chErrorBarMinusValues                             13

*** Constant Group: ChartMarkerStyleEnum
#define chMarkerStyleNone                                 0
#define chMarkerStyleSquare                               1
#define chMarkerStyleDiamond                              2
#define chMarkerStyleTriangle                             3
#define chMarkerStyleX                                    4
#define chMarkerStyleStar                                 5
#define chMarkerStyleDot                                  6
#define chMarkerStyleDash                                 7
#define chMarkerStyleCircle                               8
#define chMarkerStylePlus                                 9

*** Constant Group: ChartTrendlineTypeEnum
#define chTrendlineTypeExponential                        0
#define chTrendlineTypeLinear                             1
#define chTrendlineTypeLogarithmic                        2
#define chTrendlineTypePolynomial                         3
#define chTrendlineTypePower                              4
#define chTrendlineTypeMovingAverage                      5

*** Constant Group: ChartChartTypeEnum
#define chChartTypeCombo3D                                -2
#define chChartTypeCombo                                  -1
#define chChartTypeColumnClustered                        0
#define chChartTypeColumnStacked                          1
#define chChartTypeColumnStacked100                       2
#define chChartTypeBarClustered                           3
#define chChartTypeBarStacked                             4
#define chChartTypeBarStacked100                          5
#define chChartTypeLine                                   6
#define chChartTypeLineStacked                            8
#define chChartTypeLineStacked100                         10
#define chChartTypeLineMarkers                            7
#define chChartTypeLineStackedMarkers                     9
#define chChartTypeLineStacked100Markers                  11
#define chChartTypeSmoothLine                             12
#define chChartTypeSmoothLineStacked                      14
#define chChartTypeSmoothLineStacked100                   16
#define chChartTypeSmoothLineMarkers                      13
#define chChartTypeSmoothLineStackedMarkers               15
#define chChartTypeSmoothLineStacked100Markers            17
#define chChartTypePie                                    18
#define chChartTypePieExploded                            19
#define chChartTypePieStacked                             20
#define chChartTypeScatterMarkers                         21
#define chChartTypeScatterLine                            25
#define chChartTypeScatterLineMarkers                     24
#define chChartTypeScatterLineFilled                      26
#define chChartTypeScatterSmoothLine                      23
#define chChartTypeScatterSmoothLineMarkers               22
#define chChartTypeBubble                                 27
#define chChartTypeBubbleLine                             28
#define chChartTypeArea                                   29
#define chChartTypeAreaStacked                            30
#define chChartTypeAreaStacked100                         31
#define chChartTypeDoughnut                               32
#define chChartTypeDoughnutExploded                       33
#define chChartTypeRadarLine                              34
#define chChartTypeRadarLineMarkers                       35
#define chChartTypeRadarLineFilled                        36
#define chChartTypeRadarSmoothLine                        37
#define chChartTypeRadarSmoothLineMarkers                 38
#define chChartTypeStockHLC                               39
#define chChartTypeStockOHLC                              40
#define chChartTypePolarMarkers                           41
#define chChartTypePolarLine                              42
#define chChartTypePolarLineMarkers                       43
#define chChartTypePolarSmoothLine                        44
#define chChartTypePolarSmoothLineMarkers                 45
#define chChartTypeColumn3D                               46
#define chChartTypeColumnClustered3D                      47
#define chChartTypeColumnStacked3D                        48
#define chChartTypeColumnStacked1003D                     49
#define chChartTypeBar3D                                  50
#define chChartTypeBarClustered3D                         51
#define chChartTypeBarStacked3D                           52
#define chChartTypeBarStacked1003D                        53
#define chChartTypeLine3D                                 54
#define chChartTypeLineOverlapped3D                       55
#define chChartTypeLineStacked3D                          56
#define chChartTypeLineStacked1003D                       57
#define chChartTypePie3D                                  58
#define chChartTypePieExploded3D                          59
#define chChartTypeArea3D                                 60
#define chChartTypeAreaOverlapped3D                       61
#define chChartTypeAreaStacked3D                          62
#define chChartTypeAreaStacked1003D                       63

*** Constant Group: ChartBoundaryValueTypeEnum
#define chBoundaryValuePercent                            0
#define chBoundaryValueAbsolute                           1

*** Constant Group: ChartSizeRepresentsEnum
#define chSizeIsWidth                                     0
#define chSizeIsArea                                      1

*** Constant Group: ChartDataSourceTypeEnum
#define chDataSourceTypeUnknown                           0
#define chDataSourceTypeSpreadsheet                       1
#define chDataSourceTypePivotTable                        3
#define chDataSourceTypeQuery                             4
#define chDataSourceTypeDSC                               5

*** Constant Group: ChartSelectionMarksEnum
#define chSelectionMarksNone                              0
#define chSelectionMarksAll                               1
#define chSelectionMarksPivot                             2

*** Constant Group: ChartPlotAggregatesEnum
#define chPlotAggregatesNone                              0
#define chPlotAggregatesSeries                            1
#define chPlotAggregatesCategories                        2
#define chPlotAggregatesCharts                            3
#define chPlotAggregatesFromTotalOrientation              4

*** Constant Group: ChartDropZonesEnum
#define chDropZoneFilter                                  0
#define chDropZoneSeries                                  1
#define chDropZoneCategories                              2
#define chDropZoneData                                    3
#define chDropZoneCharts                                  4

*** Constant Group: MsoAppLanguageID
#define msoLanguageIDInstall                              1
#define msoLanguageIDUI                                   2
#define msoLanguageIDHelp                                 3
#define msoLanguageIDExeMode                              4
#define msoLanguageIDUIPrevious                           5

*** Constant Group: MsoLanguageID
#define msoLanguageIDMixed                                -2
#define msoLanguageIDNone                                 0
#define msoLanguageIDNoProofing                           1024
#define msoLanguageIDAfrikaans                            1078
#define msoLanguageIDAlbanian                             1052
#define msoLanguageIDArabicAlgeria                        5121
#define msoLanguageIDArabicBahrain                        15361
#define msoLanguageIDArabicEgypt                          3073
#define msoLanguageIDArabicIraq                           2049
#define msoLanguageIDArabicJordan                         11265
#define msoLanguageIDArabicKuwait                         13313
#define msoLanguageIDArabicLebanon                        12289
#define msoLanguageIDArabicLibya                          4097
#define msoLanguageIDArabicMorocco                        6145
#define msoLanguageIDArabicOman                           8193
#define msoLanguageIDArabicQatar                          16385
#define msoLanguageIDArabic                               1025
#define msoLanguageIDArabicSyria                          10241
#define msoLanguageIDArabicTunisia                        7169
#define msoLanguageIDArabicUAE                            14337
#define msoLanguageIDArabicYemen                          9217
#define msoLanguageIDArmenian                             1067
#define msoLanguageIDAssamese                             1101
#define msoLanguageIDAzeriCyrillic                        2092
#define msoLanguageIDAzeriLatin                           1068
#define msoLanguageIDBasque                               1069
#define msoLanguageIDByelorussian                         1059
#define msoLanguageIDBengali                              1093
#define msoLanguageIDBulgarian                            1026
#define msoLanguageIDBurmese                              1109
#define msoLanguageIDCatalan                              1027
#define msoLanguageIDChineseHongKong                      3076
#define msoLanguageIDChineseMacao                         5124
#define msoLanguageIDSimplifiedChinese                    2052
#define msoLanguageIDChineseSingapore                     4100
#define msoLanguageIDTraditionalChinese                   1028
#define msoLanguageIDCroatian                             1050
#define msoLanguageIDCzech                                1029
#define msoLanguageIDDanish                               1030
#define msoLanguageIDBelgianDutch                         2067
#define msoLanguageIDDutch                                1043
#define msoLanguageIDEnglishAUS                           3081
#define msoLanguageIDEnglishBelize                        10249
#define msoLanguageIDEnglishCanadian                      4105
#define msoLanguageIDEnglishCaribbean                     9225
#define msoLanguageIDEnglishIreland                       6153
#define msoLanguageIDEnglishJamaica                       8201
#define msoLanguageIDEnglishNewZealand                    5129
#define msoLanguageIDEnglishPhilippines                   13321
#define msoLanguageIDEnglishSouthAfrica                   7177
#define msoLanguageIDEnglishTrinidad                      11273
#define msoLanguageIDEnglishUK                            2057
#define msoLanguageIDEnglishUS                            1033
#define msoLanguageIDEnglishZimbabwe                      12297
#define msoLanguageIDEstonian                             1061
#define msoLanguageIDFaeroese                             1080
#define msoLanguageIDFarsi                                1065
#define msoLanguageIDFinnish                              1035
#define msoLanguageIDBelgianFrench                        2060
#define msoLanguageIDFrenchCameroon                       11276
#define msoLanguageIDFrenchCanadian                       3084
#define msoLanguageIDFrenchCotedIvoire                    12300
#define msoLanguageIDFrench                               1036
#define msoLanguageIDFrenchLuxembourg                     5132
#define msoLanguageIDFrenchMali                           13324
#define msoLanguageIDFrenchMonaco                         6156
#define msoLanguageIDFrenchReunion                        8204
#define msoLanguageIDFrenchSenegal                        10252
#define msoLanguageIDSwissFrench                          4108
#define msoLanguageIDFrenchWestIndies                     7180
#define msoLanguageIDFrenchZaire                          9228
#define msoLanguageIDFrisianNetherlands                   1122
#define msoLanguageIDGaelicIreland                        2108
#define msoLanguageIDGaelicScotland                       1084
#define msoLanguageIDGalician                             1110
#define msoLanguageIDGeorgian                             1079
#define msoLanguageIDGermanAustria                        3079
#define msoLanguageIDGerman                               1031
#define msoLanguageIDGermanLiechtenstein                  5127
#define msoLanguageIDGermanLuxembourg                     4103
#define msoLanguageIDSwissGerman                          2055
#define msoLanguageIDGreek                                1032
#define msoLanguageIDGujarati                             1095
#define msoLanguageIDHebrew                               1037
#define msoLanguageIDHindi                                1081
#define msoLanguageIDHungarian                            1038
#define msoLanguageIDIcelandic                            1039
#define msoLanguageIDIndonesian                           1057
#define msoLanguageIDItalian                              1040
#define msoLanguageIDSwissItalian                         2064
#define msoLanguageIDJapanese                             1041
#define msoLanguageIDKannada                              1099
#define msoLanguageIDKashmiri                             1120
#define msoLanguageIDKazakh                               1087
#define msoLanguageIDKhmer                                1107
#define msoLanguageIDKirghiz                              1088
#define msoLanguageIDKonkani                              1111
#define msoLanguageIDKorean                               1042
#define msoLanguageIDLao                                  1108
#define msoLanguageIDLatvian                              1062
#define msoLanguageIDLithuanian                           1063
#define msoLanguageIDMacedonian                           1071
#define msoLanguageIDMalaysian                            1086
#define msoLanguageIDMalayBruneiDarussalam                2110
#define msoLanguageIDMalayalam                            1100
#define msoLanguageIDMaltese                              1082
#define msoLanguageIDManipuri                             1112
#define msoLanguageIDMarathi                              1102
#define msoLanguageIDMongolian                            1104
#define msoLanguageIDNepali                               1121
#define msoLanguageIDNorwegianBokmol                      1044
#define msoLanguageIDNorwegianNynorsk                     2068
#define msoLanguageIDOriya                                1096
#define msoLanguageIDPolish                               1045
#define msoLanguageIDBrazilianPortuguese                  1046
#define msoLanguageIDPortuguese                           2070
#define msoLanguageIDPunjabi                              1094
#define msoLanguageIDRhaetoRomanic                        1047
#define msoLanguageIDRomanianMoldova                      2072
#define msoLanguageIDRomanian                             1048
#define msoLanguageIDRussianMoldova                       2073
#define msoLanguageIDRussian                              1049
#define msoLanguageIDSamiLappish                          1083
#define msoLanguageIDSanskrit                             1103
#define msoLanguageIDSerbianCyrillic                      3098
#define msoLanguageIDSerbianLatin                         2074
#define msoLanguageIDSesotho                              1072
#define msoLanguageIDSindhi                               1113
#define msoLanguageIDSlovak                               1051
#define msoLanguageIDSlovenian                            1060
#define msoLanguageIDSorbian                              1070
#define msoLanguageIDSpanishArgentina                     11274
#define msoLanguageIDSpanishBolivia                       16394
#define msoLanguageIDSpanishChile                         13322
#define msoLanguageIDSpanishColombia                      9226
#define msoLanguageIDSpanishCostaRica                     5130
#define msoLanguageIDSpanishDominicanRepublic             7178
#define msoLanguageIDSpanishEcuador                       12298
#define msoLanguageIDSpanishElSalvador                    17418
#define msoLanguageIDSpanishGuatemala                     4106
#define msoLanguageIDSpanishHonduras                      18442
#define msoLanguageIDMexicanSpanish                       2058
#define msoLanguageIDSpanishNicaragua                     19466
#define msoLanguageIDSpanishPanama                        6154
#define msoLanguageIDSpanishParaguay                      15370
#define msoLanguageIDSpanishPeru                          10250
#define msoLanguageIDSpanishPuertoRico                    20490
#define msoLanguageIDSpanishModernSort                    3082
#define msoLanguageIDSpanish                              1034
#define msoLanguageIDSpanishUruguay                       14346
#define msoLanguageIDSpanishVenezuela                     8202
#define msoLanguageIDSutu                                 1072
#define msoLanguageIDSwahili                              1089
#define msoLanguageIDSwedishFinland                       2077
#define msoLanguageIDSwedish                              1053
#define msoLanguageIDTajik                                1064
#define msoLanguageIDTamil                                1097
#define msoLanguageIDTatar                                1092
#define msoLanguageIDTelugu                               1098
#define msoLanguageIDThai                                 1054
#define msoLanguageIDTibetan                              1105
#define msoLanguageIDTsonga                               1073
#define msoLanguageIDTswana                               1074
#define msoLanguageIDTurkish                              1055
#define msoLanguageIDTurkmen                              1090
#define msoLanguageIDUkrainian                            1058
#define msoLanguageIDUrdu                                 1056
#define msoLanguageIDUzbekCyrillic                        2115
#define msoLanguageIDUzbekLatin                           1091
#define msoLanguageIDVenda                                1075
#define msoLanguageIDVietnamese                           1066
#define msoLanguageIDWelsh                                1106
#define msoLanguageIDXhosa                                1076
#define msoLanguageIDZulu                                 1077

*** Constant Group: XlBorderWeight
#define xlHairline                                        1
#define xlThin                                            2
#define xlMedium                                          -4138
#define xlThick                                           4

*** Constant Group: XlColorIndex
#define xlColorIndexAutomatic                             -4105
#define xlColorIndexNone                                  -4142

*** Constant Group: XlSearchDirection
#define xlNext                                            1
#define xlPrevious                                        2

*** Constant Group: XlSortOrder
#define xlAscending                                       1
#define xlDescending                                      2

*** Constant Group: XlYesNoGuess
#define xlGuess                                           0
#define xlYes                                             1
#define xlNo                                              2

*** Constant Group: XlReferenceStyle
#define xlA1                                              1
#define xlR1C1                                            -4150

*** Constant Group: SheetExportActionEnum
#define ssExportActionNone                                0
#define ssExportActionOpenInExcel                         1

*** Constant Group: SheetExportFormat
#define ssExportAsAppropriate                             0
#define ssExportXMLSpreadsheet                            1
#define ssExportHTML                                      2

*** Constant Group: SheetFilterFunction
#define ssFilterFunctionInclude                           1
#define ssFilterFunctionExclude                           2

*** Constant Group: XlWindowType
#define xlWorkbook                                        1

*** Constant Group: XlSheetType
#define xlWorksheet                                       -4167

*** Constant Group: XlSheetVisibility
#define xlSheetVisible                                    -1
#define xlSheetHidden                                     0
#define xlSheetVeryHidden                                 2

*** Constant Group: XlCalculation
#define xlCalculationAutomatic                            -4105
#define xlCalculationManual                               -4135

*** Constant Group: XlDirection
#define xlDown                                            -4121
#define xlToLeft                                          -4159
#define xlToRight                                         -4161
#define xlUp                                              -4162

*** Constant Group: XlUnderlineStyle
#define xlUnderlineStyleNone                              -4142
#define xlUnderlineStyleSingle                            2
#define xlUnderlineStyleDouble                            -4119
#define xlUnderlineStyleSingleAccounting                  4
#define xlUnderlineStyleDoubleAccounting                  5

*** Constant Group: XlBordersIndex
#define xlEdgeLeft                                        7
#define xlEdgeTop                                         8
#define xlEdgeBottom                                      9
#define xlEdgeRight                                       10
#define xlInsideVertical                                  11
#define xlInsideHorizontal                                12

*** Constant Group: XlLineStyle
#define xlLineStyleNone                                   -4142
#define xlContinuous                                      1
#define xlDash                                            -4115
#define xlDot                                             -4118
#define xlDashDot                                         4
#define xlDashDotDot                                      5

*** Constant Group: XlHAlign
#define xlHAlignGeneral                                   1
#define xlHAlignLeft                                      -4131
#define xlHAlignCenter                                    -4108
#define xlHAlignRight                                     -4152
#define xlHAlignFill                                      5

*** Constant Group: XlReadingOrder
#define xlContext                                         -5002
#define xlLTR                                             -5003
#define xlRTL                                             -5004

*** Constant Group: XlVAlign
#define xlVAlignBottom                                    -4107
#define xlVAlignCenter                                    -4108
#define xlVAlignTop                                       -4160

*** Constant Group: TipTypeEnum
#define eTipTypeNone                                      -1
#define eTipTypeText                                      0
#define eTipTypeHTML                                      1
#define eTipTypeAuto                                      2

*** Constant Group: LineStyleEnum
#define owcLineStyleNone                                  0
#define owcLineStyleAutomatic                             1
#define owcLineStyleSolid                                 2
#define owcLineStyleDash                                  3
#define owcLineStyleDot                                   4
#define owcLineStyleDashDot                               5
#define owcLineStyleDashDotDot                            6

*** Constant Group: ExpandBitmapTypeEnum
#define ecBitmapPlusMinus                                 0
#define ecBitmapUpDownArrow                               1
#define ecBitmapOpenCloseFolder                           2

*** Constant Group: DscFieldTypeEnum
#define dscParameter                                      -1
#define dscOutput                                         1
#define dscCalculated                                     2
#define dscGrouping                                       3

*** Constant Group: DscTotalTypeEnum
#define dscNone                                           0
#define dscSum                                            1
#define dscAvg                                            2
#define dscMin                                            3
#define dscMax                                            4
#define dscCount                                          5
#define dscAny                                            6
#define dscStdev                                          7

*** Constant Group: DscGroupOnEnum
#define dscEachValue                                      0
#define dscPrefix                                         1
#define dscYear                                           2
#define dscQuarter                                        3
#define dscMonth                                          4
#define dscWeek                                           5
#define dscDay                                            6
#define dscHour                                           7
#define dscMinute                                         8
#define dscInterval                                       9

*** Constant Group: DscJoinTypeEnum
#define dscInnerJoin                                      1
#define dscLeftOuterJoin                                  2
#define dscRightOuterJoin                                 3

*** Constant Group: DscPageRelTypeEnum
#define dscSublist                                        1
#define dscLookup                                         2

*** Constant Group: DscObjectTypeEnum
#define dscobjUnknown                                     -1
#define dscobjSchemaRowsource                             1
#define dscobjSchemaField                                 2
#define dscobjSchemaRelationship                          4
#define dscobjRecordsetDef                                8
#define dscobjPageRowsource                               16
#define dscobjPageField                                   32
#define dscobjSublistRelationship                         64
#define dscobjLookupRelationship                          128
#define dscobjGroupingDef                                 256
#define dscobjDatamodel                                   512
#define dscobjPageRelatedField                            1024
#define dscobjParameterValue                              2048
#define dscobjSchemaRelatedField                          4096
#define dscobjSchemaParameter                             8192
#define dscobjSchemaProperty                              16384
#define dscobjSchemaDiagram                               32768

*** Constant Group: NavButtonEnum
#define navbtnMoveFirst                                   0
#define navbtnMovePrev                                    1
#define navbtnMoveNext                                    2
#define navbtnMoveLast                                    3
#define navbtnNew                                         4
#define navbtnDelete                                      5
#define navbtnSave                                        6
#define navbtnUndo                                        7
#define navbtnSortAscending                               8
#define navbtnSortDescending                              9
#define navbtnApplyFilter                                 10
#define navbtnToggleFilter                                11
#define navbtnHelp                                        12

*** Constant Group: DscDropTypeEnum
#define dscDefault                                        0
#define dscGrid                                           1
#define dscFields                                         2

*** Constant Group: DscDropLocationEnum
#define dscAbove                                          1
#define dscWithin                                         2
#define dscBelow                                          3

*** Constant Group: DscHyperlinkPartEnum
#define dschlDisplayedValue                               0
#define dschlDisplayText                                  1
#define dschlAddress                                      2
#define dschlSubAddress                                   3
#define dschlScreenTip                                    4
#define dschlFullAddress                                  5

*** Constant Group: DscLocationEnum
#define dscSystem                                         -1
#define dscClient                                         0
#define dscServer                                         1

*** Constant Group: DscRecordsetTypeEnum
#define dscSnapshot                                       1
#define dscUpdatableSnapshot                              2

*** Constant Group: DscRowsourceTypeEnum
#define dscTable                                          1
#define dscView                                           2
#define dscCommandText                                    3
#define dscProcedure                                      4
#define dscCommandFile                                    5

*** Constant Group: DscFetchTypeEnum
#define dscFull                                           1
#define dscParameterized                                  2
#define dscSelectControl                                  32768

*** Constant Group: DscAdviseTypeEnum
#define dscAdd                                            1
#define dscDelete                                         2
#define dscMove                                           3
#define dscLoad                                           4
#define dscChange                                         5
#define dscDeleteComplete                                 6
#define dscRename                                         7

*** Constant Group: OCCommandId
#define ocCommandAbout                                    1007
#define ocCommandUndo                                     1000
#define ocCommandCut                                      1001
#define ocCommandCopy                                     1002
#define ocCommandPaste                                    1003
#define ocCommandProperties                               1005
#define ocCommandHelp                                     1006
#define ocCommandExport                                   1004
#define ocCommandSortAsc                                  2000
#define ocCommandSortDesc                                 2031
#define ocCommandChooser                                  1010
#define ocCommandAutoFilter                               1017
#define ocCommandAutoCalc                                 1016
#define ocCommandCollapse                                 1013
#define ocCommandExpand                                   1012
#define ocCommandRefresh                                  1014

*** Constant Group: XlApplicationInternational
#define xl24HourClock                                     33
#define xl4DigitYears                                     43
#define xlAlternateArraySeparator                         16
#define xlColumnSeparator                                 14
#define xlCountryCode                                     1
#define xlCountrySetting                                  2
#define xlCurrencyBefore                                  37
#define xlCurrencyCode                                    25
#define xlCurrencyDigits                                  27
#define xlCurrencyLeadingZeros                            40
#define xlCurrencyMinusSign                               38
#define xlCurrencyNegative                                28
#define xlCurrencySpaceBefore                             36
#define xlCurrencyTrailingZeros                           39
#define xlDateOrder                                       32
#define xlDateSeparator                                   17
#define xlDayCode                                         21
#define xlDayLeadingZero                                  42
#define xlDecimalSeparator                                3
#define xlGeneralFormatName                               26
#define xlHourCode                                        22
#define xlLeftBrace                                       12
#define xlLeftBracket                                     10
#define xlListSeparator                                   5
#define xlLowerCaseColumnLetter                           9
#define xlLowerCaseRowLetter                              8
#define xlMDY                                             44
#define xlMetric                                          35
#define xlMinuteCode                                      23
#define xlMonthCode                                       20
#define xlMonthLeadingZero                                41
#define xlMonthNameChars                                  30
#define xlNoncurrencyDigits                               29
#define xlNonEnglishFunctions                             34
#define xlRightBrace                                      13
#define xlRightBracket                                    11
#define xlRowSeparator                                    15
#define xlSecondCode                                      24
#define xlThousandsSeparator                              4
#define xlTimeLeadingZero                                 45
#define xlTimeSeparator                                   18
#define xlUpperCaseColumnLetter                           7
#define xlUpperCaseRowLetter                              6
#define xlWeekdayNameChars                                31
#define xlYearCode                                        19

*** Constant Group: FieldListRelationshipTypeEnum
#define flrelNoRel                                        0
#define flrelOneToMany                                    1
#define flrelManyToOne                                    2
#define flrelOneToOnePrimaryPrimary                       4
#define flrelOneToOnePrimaryForeign                       8
#define flrelUniqueConstraint                             16
#define flrelUniqueIndex                                  32

*** Constant Group: FieldListObjectTypeEnum
#define flTables                                          1
#define flViews                                           2
#define flStoredProcedures                                4
#define flCmdText                                         8
#define flSchemaDiagrams                                  16
#define flOLAPCube                                        32
#define flAll                                             63

*** Constant Group: DaAttrEnum
#define daLength                                          1
#define daPrecision                                       2
#define daScale                                           3

*** Constant Group: SectTypeEnum
#define sectTypeNone                                      0
#define sectTypeCaption                                   1
#define sectTypeHeader                                    2
#define sectTypeFooter                                    3
#define sectTypeRecNav                                    4

*** Constant Group: DscStatusEnum
#define dscDeleteOK                                       0
#define dscDeleteCancel                                   1
#define dscDeleteUserCancel                               2

*** Constant Group: DscDisplayAlert
#define dscDataAlertContinue                              0
#define dscDataAlertDisplay                               1

*** Constant Group: DefaultControlTypeEnum
#define ctlTypeTextBox                                    0
#define ctlTypeBoundSpan                                  1
#define ctlTypeBoundHTML                                  1

*** Constant Group: DataPageDesignerFlags
#define designFlagDontDelete                              1
#define designFlagDontCleanup                             2

*** Constant Group: ExportableConnectStringEnum
#define exportNone                                        0
#define exportForExcel                                    1

*** Constant Group: DscOfflineTypeEnum
#define dscOfflineNone                                    0
#define dscOfflineMerge                                   1
#define dscOfflineXMLDataFile                             2

*** Constant Group: DscXMLLocationEnum
#define dscXMLEmbedded                                    0
#define dscXMLDataFile                                    1

*** Constant Group: DscSaveAsEnum
#define dscSaveAsEmbeddedXML                              0
#define dscSaveAsXMLDataFile                              1

*** Constant Group: DscEncodingEnum
#define dscUTF8                                           0
#define dscUTF16                                          1

*** Constant Group: NotificationType
#define dscConnectionReset                                0
#define dscDataReset                                      1

*** Constant Group: RefreshType
#define dscRefreshConnection                              0
#define dscRefreshData                                    1

*** Constant Group: SynchronizationStatus
#define dscSynchronizing                                  0
#define dscSynchronizationDone                            1

*** Constant Group: FieldListSelectRestriction
#define flSRNone                                          0
#define flSRParent                                        1
#define flSRParentAndType                                 2

*** Constant Group: ChartFillStyleEnum
#define chNone                                            -1
#define chSolid                                           0

*** Constant Group: ChartColorIndexEnum
#define chColorAutomatic                                  -1
#define chColorNone                                       -2

*** Constant Group: ChartDataGroupingFunctionEnum
#define chDataGroupingFunctionMinimum                     0
#define chDataGroupingFunctionMaximum                     1
#define chDataGroupingFunctionSum                         2
#define chDataGroupingFunctionAverage                     3

*** Constant Group: ChartSeriesByEnum
#define chSeriesByRows                                    0
#define chSeriesByColumns                                 1

*** Constant Group: ChartSpecialDataSourcesEnum
#define chDataBound                                       0
#define chDataLiteral                                     -1
#define chDataNone                                        -2
#define chDataLinked                                      -3

*** Constant Group: ChartPivotDataReferenceEnum
#define chPivotColumns                                    -1
#define chPivotRows                                       -2
#define chPivotColAggregates                              -3
#define chPivotRowAggregates                              -4

*** Constant Group: Chart3DSurfaceEnum
#define chSurfaceBackWall                                 0
#define chSurfaceSideWall                                 1
#define chSurfaceFloor                                    2

*** Constant Group: ChartLabelOrientationEnum
#define chLabelOrientationAutomatic                       1000
#define chLabelOrientationHorizontal                      0
#define chLabelOrientationUpward                          90
#define chLabelOrientationDownward                        -90

*** Constant Group: ChartCommandIdEnum
#define chCommandCut                                      1001
#define chCommandDeleteSelection                          1011
#define chCommandShowPropertyToolbox                      1005
#define chCommandShowContextMenu                          6001
#define chCommandUndo                                     1000
#define chCommandSelectPrevMinor                          6002
#define chCommandSelectNextMinor                          6003
#define chCommandSelectPrevMajor                          6004
#define chCommandSelectNextMajor                          6005
#define chCommandShowHelp                                 1006
#define chCommandShowAbout                                1007
#define chCommandPassiveAlert                             6026
#define chCommandLaunchDataFinder                         6027
#define chCommandShowLegend                               6028
#define chCommandRefresh                                  1014
#define chCommandByRowCol                                 6032
#define chCommandSortAscending                            2000
#define chCommandSortDescending                           2031
#define chCommandAutoFilter                               1017
#define chCommandAutoCalc                                 1016
#define chCommandExpand                                   1012
#define chCommandCollapse                                 1013
#define chCommandDrill                                    6034
#define chCommandFieldList                                1010
#define chCommandFilterByMenu                             1015
#define chCommandSortAscendingByTotal                     6035
#define chCommandSortDescendingByTotal                    6036
#define chCommandDrillOut                                 6037
#define chCommandTogglePropertiesInScreenTip              6038
#define chCommandChartType                                6039
#define chCommandShowWizard                               6040
#define chCommandSum                                      6041
#define chCommandCount                                    6042
#define chCommandMin                                      6043
#define chCommandMax                                      6044
#define chCommandAverage                                  6045
#define chCommandStdDev                                   6046
#define chCommandVar                                      6047
#define chCommandStdDevP                                  6048
#define chCommandVarP                                     6049
#define chCommandFontName                                 1050
#define chCommandFontSize                                 1051
#define chCommandBold                                     1052
#define chCommandItalic                                   1053
#define chCommandUnderline                                1054
#define chCommandLineColor                                1055
#define chCommandInteriorColor                            1056
#define chCommandFontColor                                1057
#define chCommandMultiChart                               6050
#define chCommandUnifiedScales                            6051
#define chCommandShowDropZones                            6052
#define chCommandShowToolbar                              6053
#define chCommandShowTop1                                 1100
#define chCommandShowTop2                                 1101
#define chCommandShowTop5                                 1102
#define chCommandShowTop10                                1103
#define chCommandShowTop25                                1104
#define chCommandShowTop1Percent                          1105
#define chCommandShowTop2Percent                          1106
#define chCommandShowTop5Percent                          1107
#define chCommandShowTop10Percent                         1108
#define chCommandShowTop25Percent                         1109
#define chCommandShowBottom1                              1110
#define chCommandShowBottom2                              1111
#define chCommandShowBottom5                              1112
#define chCommandShowBottom10                             1113
#define chCommandShowBottom25                             1114
#define chCommandShowBottom1Percent                       1115
#define chCommandShowBottom2Percent                       1116
#define chCommandShowBottom5Percent                       1117
#define chCommandShowBottom10Percent                      1118
#define chCommandShowBottom25Percent                      1119
#define chCommandShowOther                                1120
#define chCommandShowAll                                  1121
#define chCommandShowTopNMenu                             1123
#define chCommandShowBottomNMenu                          1124
#define chCommandConditionalFilter                        1125
#define chCommandMoveToFilterArea                         6054
#define chCommandMoveToSeriesArea                         6055
#define chCommandMoveToCategoryArea                       6056
#define chCommandMoveToChartArea                          6057

*** Constant Group: AddinClientTypeEnum
#define ssCoerceNum                                       1
#define ssCoerceStr                                       2
#define ssCoerceBool                                      4
#define ssCoerceErr                                       16
#define ssCoerceMulti                                     64
#define ssCoerceInt                                       2048

*** Constant Group: SpreadSheetCommandId
#define ssCommandUndo                                     1000
#define ssCommandCut                                      1001
#define ssCommandCopy                                     1002
#define ssCommandPaste                                    1003
#define ssCommandExport                                   1004
#define ssCommandProperties                               1005
#define ssCommandHelp                                     1006
#define ssCommandAbout                                    1007
#define ssCommandSortAsc                                  2000
#define ssCommandSortAscLast                              2030
#define ssCommandSortDesc                                 2031
#define ssCommandSortDescLast                             2061
#define ssCommandAutosum                                  10000
#define ssCommandAutoFilter                               10001
#define ssCommandClear                                    10002
#define ssCommandBold                                     1052
#define ssCommandItalic                                   1053
#define ssCommandUnderline                                1054
#define ssCommandDeleteRows                               10006
#define ssCommandDeleteCols                               10007
#define ssCommandInsertRows                               10008
#define ssCommandInsertCols                               10009
#define ssCommandRecalcForce                              10010
#define ssCommandSelectRow                                10011
#define ssCommandSelectCol                                10012
#define ssCommandSelectAll                                10013
#define ssCommandMoveLeft                                 10014
#define ssCommandMoveUp                                   10015
#define ssCommandMoveRight                                10016
#define ssCommandMoveDown                                 10017
#define ssCommandScrollLeft                               10018
#define ssCommandScrollUp                                 10019
#define ssCommandScrollRight                              10020
#define ssCommandScrollDown                               10021
#define ssCommandMoveNext                                 10022
#define ssCommandMovePrevious                             10023
#define ssCommandTabNext                                  10024
#define ssCommandTabPrevious                              10025
#define ssCommandMoveToEndLeft                            10026
#define ssCommandMoveToEndUp                              10027
#define ssCommandMoveToEndRight                           10028
#define ssCommandMoveToEndDown                            10029
#define ssCommandExpandLeft                               10030
#define ssCommandExpandUp                                 10031
#define ssCommandExpandRight                              10032
#define ssCommandExpandDown                               10033
#define ssCommandExpandToEndLeft                          10034
#define ssCommandExpandToEndUp                            10035
#define ssCommandExpandToEndRight                         10036
#define ssCommandExpandToEndDown                          10037
#define ssCommandEnterEditMode                            10038
#define ssCommandShowContextMenu                          10039
#define ssCommandToggleToolbar                            10040
#define ssCommandEscape                                   10041
#define ssCommandMoveToLast                               10042
#define ssCommandExpandToLast                             10043
#define ssCommandMoveToLastInRow                          10044
#define ssCommandMovePageDown                             10045
#define ssCommandExpandPageDown                           10046
#define ssCommandMovePageUp                               10047
#define ssCommandExpandPageUp                             10048
#define ssCommandMovePageRight                            10062
#define ssCommandExpandPageRight                          10063
#define ssCommandMovePageLeft                             10064
#define ssCommandExpandPageLeft                           10065
#define ssCommandMoveToOrigin                             10049
#define ssCommandExpandToOrigin                           10050
#define ssCommandMoveToHome                               10051
#define ssCommandExpandToHome                             10052
#define ssCommandExpandMenu                               10053
#define ssCommandEat                                      10054
#define ssCommandNextSheet                                10055
#define ssCommandPrevSheet                                10056
#define ssCommandNewSheet                                 10057
#define ssCommandSelectArray                              10058
#define ssCommandSelectArraySilent                        10067
#define ssCommandRecalc                                   10059
#define ssCommandRefresh                                  10060
#define ssCommandRefreshAll                               10061
#define ssCommandMakeActiveCellVisible                    10066

*** Constant Group: SheetCommandEnum
#define ssCalculate                                       0
#define ssInsertRows                                      2
#define ssInsertColumns                                   3
#define ssDeleteRows                                      4
#define ssDeleteColumns                                   5
#define ssCut                                             6
#define ssCopy                                            7
#define ssPaste                                           8
#define ssExport                                          9
#define ssUndo                                            10
#define ssSortAscending                                   11
#define ssSortDescending                                  12
#define ssFind                                            13
#define ssClear                                           14
#define ssAutoFilter                                      15
#define ssProperties                                      16
#define ssHelp                                            17

*** Constant Group: XlConstants
#define xlAutomatic                                       -4105
#define xlNone                                            -4142

*** Constant Group: XlDeleteShiftDirection
#define xlShiftToLeft                                     -4159
#define xlShiftUp                                         -4162

*** Constant Group: XlInsertShiftDirection
#define xlShiftDown                                       -4121
#define xlShiftToRight                                    -4161

*** Constant Group: XlFindLookIn
#define xlFormulas                                        -4123
#define xlValues                                          -4163

*** Constant Group: XlLookAt
#define xlPart                                            2
#define xlWhole                                           1

*** Constant Group: XlOrientation
#define xlDownward                                        -4170
#define xlHorizontal                                      -4128
#define xlUpward                                          -4171
#define xlVertical                                        -4166

*** Constant Group: XlSearchOrder
#define xlByColumns                                       2
#define xlByRows                                          1

*** Constant Group: XlRangeValueType
#define xlRangeValueDefault                               10
#define xlRangeValueXMLSpreadsheet                        11
#define xlRangeValueHTML                                  1000
#define xlRangeValueCSV                                   1001

*** Constant Group: PivotViewReasonEnum
#define plViewReasonSelectionChange                       0
#define plViewReasonSystemColorChange                     1
#define plViewReasonDataChange                            2
#define plViewReasonFontNameChange                        3
#define plViewReasonFontSizeChange                        4
#define plViewReasonFontBoldChange                        5
#define plViewReasonFontItalicChange                      6
#define plViewReasonFontUnderlineChange                   7
#define plViewReasonMemberExpandedChange                  8
#define plViewReasonCellExpandedChange                    9
#define plViewReasonDetailRowHeightChange                 10
#define plViewReasonFieldDetailWidthChange                11
#define plViewReasonFieldGroupedWidthChange               12
#define plViewReasonViewDetailWidthChange                 13
#define plViewReasonFieldSetWidthChange                   14
#define plViewReasonTotalWidthChange                      15
#define plViewReasonForeColorChange                       16
#define plViewReasonBackColorChange                       17
#define plViewReasonAlignmentChange                       18
#define plViewReasonNumberFormatChange                    19
#define plViewReasonDetailTopChange                       20
#define plViewReasonDetailLeftChange                      21
#define plViewReasonTopChange                             22
#define plViewReasonLeftChange                            23
#define plViewReasonRightToLeftChange                     24
#define plViewReasonTotalOrientationChange                25
#define plViewReasonDisplayOutlineChange                  26
#define plViewReasonFieldCaptionChange                    27
#define plViewReasonFieldSetCaptionChange                 28
#define plViewReasonLabelCaptionChange                    29
#define plViewReasonMemberCaptionChange                   30
#define plViewReasonTotalCaptionChange                    31
#define plViewReasonAllowFilteringChange                  32
#define plViewReasonAllowGroupingChange                   33
#define plViewReasonWidthChange                           34
#define plViewReasonHeightChange                          35
#define plViewReasonLabelVisibleChange                    36
#define plViewReasonDisplayToolbarChange                  37
#define plViewReasonMaxHeightChange                       38
#define plViewReasonMaxWidthChange                        39
#define plViewReasonAutoFitChange                         40
#define plViewReasonFieldExpandedChange                   41
#define plViewReasonExpandDetailsChange                   42
#define plViewReasonDetailMaxWidthChange                  43
#define plViewReasonDetailMaxHeightChange                 44
#define plViewReasonTopOffsetChange                       45
#define plViewReasonLeftOffsetChange                      46
#define plViewReasonDetailTopOffsetChange                 47
#define plViewReasonDetailLeftOffsetChange                48
#define plViewReasonIsHyperlinkChange                     49
#define plViewReasonMemberPropertyDisplayInChange         50
#define plViewReasonMemberPropertyCaptionChange           51
#define plViewReasonMemberPropertiesOrderChange           52
#define plViewReasonFieldGroupedHeightChange              53
#define plViewReasonMemberHeightChange                    54
#define plViewReasonMemberWidthChange                     55
#define plViewReasonPropertyValueWidthChange              56
#define plViewReasonPropertyHeightChange                  57
#define plViewReasonShowDetails                           58
#define plViewReasonHideDetails                           59
#define plViewReasonAllowCustomOrderingChange             60
#define plViewReasonAllowPropertyToolbox                  61
#define plViewReasonExpandMembersChange                   62
#define plViewReasonAllowEditsChange                      63
#define plViewReasonAllowAdditionsChange                  64
#define plViewReasonAllowDeletionsChange                  65
#define plViewReasonSetFocus                              66
#define plViewReasonKillFocus                             67
#define plViewReasonDisplayScreenTipsChange               68
#define plViewReasonShowAsChange                          69
#define plViewReasonMemberCaptionsChange                  70
#define plViewReasonPropertyCaptionWidthChange            71
#define plViewReasonDataMemberCaptionChange               72
#define plViewReasonDisplayInFieldListChange              73
#define plViewReasonToolbarChange                         74
#define plViewReasonUseProviderFormattingChange           75

*** Constant Group: PivotDataReasonEnum
#define plDataReasonInsertFieldSet                        0
#define plDataReasonRemoveFieldSet                        1
#define plDataReasonInsertTotal                           2
#define plDataReasonRemoveTotal                           3
#define plDataReasonAllowDetailsChange                    4
#define plDataReasonSortDirectionChange                   5
#define plDataReasonSortOnChange                          6
#define plDataReasonSortOnScopeChange                     7
#define plDataReasonFilterFunctionChange                  8
#define plDataReasonFilterContextChange                   9
#define plDataReasonDisplayCalculatedMembersChange        10
#define plDataReasonFilterOnChange                        11
#define plDataReasonFilterOnScopeChange                   12
#define plDataReasonFilterFunctionValueChange             13
#define plDataReasonTotalNameChange                       14
#define plDataReasonIncludedMembersChange                 15
#define plDataReasonExcludedMembersChange                 16
#define plDataReasonIsIncludedChange                      17
#define plDataReasonDisplayEmptyMembersChange             19
#define plDataReasonTotalFunctionChange                   20
#define plDataReasonUser                                  21
#define plDataReasonDataSourceChange                      22
#define plDataReasonDataMemberChange                      23
#define plDataReasonGroupOnChange                         24
#define plDataReasonUnknown                               25
#define plDataReasonGroupStartChange                      26
#define plDataReasonGroupIntervalChange                   27
#define plDataReasonIsFilteredChange                      28
#define plDataReasonOrderedMembersChange                  29
#define plDataReasonGroupEndChange                        30
#define plDataReasonCommandTextChange                     31
#define plDataReasonConnectionStringChange                32
#define plDataReasonMemberPropertyIsIncludedChange        33
#define plDataReasonMemberPropertyDisplayInChange         34
#define plDataReasonSubtotalsChange                       35
#define plDataReasonTotalExpressionChange                 36
#define plDataReasonTotalSolveOrderChange                 37
#define plDataReasonTotalDeleted                          38
#define plDataReasonFieldSetDeleted                       39
#define plDataReasonRecordChanged                         40
#define plDataReasonAllowMultiFilterChange                41
#define plDataReasonAllIncludeExcludeChange               42
#define plDataReasonAdhocFieldAdded                       43
#define plDataReasonAdhocFieldDeleted                     44
#define plDataReasonAdhocMemberChanged                    45
#define plDataReasonAlwaysIncludeInCubeChange             46
#define plDataReasonExpressionChange                      47
#define plDataReasonTotalAllMembersChange                 48
#define plDataReasonDisplayCellColorChange                49
#define plDataReasonFilterCrossJoinsChange                50
#define plDataReasonRefreshDataSource                     51
#define plDataReasonFieldSetNameChange                    52
#define plDataReasonFieldNameChange                       53

*** Constant Group: PivotTableReasonEnum
#define plPivotTableReasonTotalAdded                      0
#define plPivotTableReasonTotalDeleted                    1
#define plPivotTableReasonFieldSetAdded                   2
#define plPivotTableReasonFieldAdded                      3

*** Constant Group: PivotCommandId
#define plCommandAbout                                    1007
#define plCommandDelete                                   1011
#define plCommandFilterBySel                              12001
#define plCommandChooser                                  1010
#define plCommandProperties                               1005
#define plCommandInsertField                              12004
#define plCommandAutoSum                                  12005
#define plCommandAutoCount                                12006
#define plCommandAutoMin                                  12007
#define plCommandAutoMax                                  12008
#define plCommandDropzones                                12009
#define plCommandRemove                                   12010
#define plCommandNextHorz                                 12012
#define plCommandNextVert                                 12013
#define plCommandLeftEdge                                 12014
#define plCommandRightEdge                                12015
#define plCommandTopLeftEdge                              12016
#define plCommandBottomRightEdge                          12017
#define plCommandNextHorzCell                             12018
#define plCommandPrevHorzCell                             12019
#define plCommandLastLeft                                 12020
#define plCommandLastRight                                12021
#define plCommandLastUp                                   12022
#define plCommandLastDown                                 12023
#define plCommandEnterDetails                             12024
#define plCommandExitDetails                              12025
#define plCommandLeft                                     12026
#define plCommandRight                                    12027
#define plCommandUp                                       12028
#define plCommandDown                                     12029
#define plCommandPageUp                                   12030
#define plCommandPageDown                                 12031
#define plCommandPageLeft                                 12032
#define plCommandPageRight                                12033
#define plCommandGroupByRow                               12034
#define plCommandGroupByColumn                            12035
#define plCommandUngroup                                  12036
#define plCommandFilter                                   12037
#define plCommandPromote                                  12038
#define plCommandDemote                                   12039
#define plCommandExpand                                   1012
#define plCommandCollapse                                 1013
#define plCommandSubtotal                                 12042
#define plCommandExport                                   1004
#define plCommandToolbar                                  12044
#define plCommandSortAsc                                  2000
#define plCommandSortDesc                                 2031
#define plCommandClearCustomOrdering                      12154
#define plCommandHelp                                     1006
#define plCommandRefresh                                  1014
#define plCommandAutoFilter                               1017
#define plCommandCopy                                     1002
#define plCommandExpandIndicator                          12051
#define plCommandSelectField                              12052
#define plCommandSelectRow                                12053
#define plCommandSelectAll                                12054
#define plCommandFormatGeneral                            12055
#define plCommandFormatCurrency                           12056
#define plCommandFormatPercent                            12057
#define plCommandFormatExponent                           12058
#define plCommandFormatDate                               12059
#define plCommandFormatTime                               12060
#define plCommandFormatComma                              12061
#define plCommandFormatBold                               12062
#define plCommandFormatItalic                             12063
#define plCommandFormatUnderline                          12064
#define plCommandFormatUnderline2                         12146
#define plCommandFilterByMenu                             12065
#define plCommandContextMenu                              12066
#define plCommandPrevHorz                                 12067
#define plCommandPrevVert                                 12068
#define plCommandNextVertCell                             12069
#define plCommandPrevVertCell                             12070
#define plCommandExtendLeft                               12072
#define plCommandExtendRight                              12073
#define plCommandExtendUp                                 12074
#define plCommandExtendDown                               12075
#define plCommandExtendPageLeft                           12076
#define plCommandExtendPageRight                          12077
#define plCommandExtendPageUp                             12078
#define plCommandExtendPageDown                           12079
#define plCommandHyperlink                                12082
#define plCommandOpenHyperlinkInPlace                     12083
#define plCommandOpenHyperlinkInWindow                    12084
#define plCommandMoveMemUp                                12085
#define plCommandMoveMemDown                              12086
#define plCommandMoveMemLeft                              12087
#define plCommandMoveMemRight                             12088
#define plCommandAutoAverage                              12089
#define plCommandAutoStdDev                               12090
#define plCommandAutoVar                                  12091
#define plCommandAutoStdDevP                              12092
#define plCommandAutoVarP                                 12093
#define plCommandShowDetails                              12095
#define plCommandHideDetails                              12096
#define plCommandTogglePropertiesInReport                 12097
#define plCommandTogglePropertiesInScreenTip              12098
#define plCommandStartEdit                                12099
#define plCommandEndEdit                                  12100
#define plCommandDeleteRow                                12101
#define plCommandCreateCalculatedTotal                    12102
#define plCommandPaste                                    1003
#define plCommandExtendTopLeftEdge                        12107
#define plCommandExtendBottomRightEdge                    12108
#define plCommandTogglePropertyInReport                   12900
#define plCommandTogglePropertyInScreenTip                12950
#define plCommandAutoCalc                                 1016
#define plCommandCalculated                               12110
#define plCommandShowTop1                                 1100
#define plCommandShowTop2                                 1101
#define plCommandShowTop5                                 1102
#define plCommandShowTop10                                1103
#define plCommandShowTop25                                1104
#define plCommandShowTop1Percent                          1105
#define plCommandShowTop2Percent                          1106
#define plCommandShowTop5Percent                          1107
#define plCommandShowTop10Percent                         1108
#define plCommandShowTop25Percent                         1109
#define plCommandShowBottom1                              1110
#define plCommandShowBottom2                              1111
#define plCommandShowBottom5                              1112
#define plCommandShowBottom10                             1113
#define plCommandShowBottom25                             1114
#define plCommandShowBottom1Percent                       1115
#define plCommandShowBottom2Percent                       1116
#define plCommandShowBottom5Percent                       1117
#define plCommandShowBottom10Percent                      1118
#define plCommandShowBottom25Percent                      1119
#define plCommandShowOther                                1120
#define plCommandShowAll                                  1121
#define plCommandShowTopNMenu                             1123
#define plCommandShowBottomNMenu                          1124
#define plCommandConditionalFilter                        1125
#define plCommandShowAs                                   12134
#define plCommandShowAsNormal                             12135
#define plCommandShowAsPercentOfRowTotal                  12136
#define plCommandShowAsPercentOfColumnTotal               12137
#define plCommandShowAsPercentOfRowParent                 12138
#define plCommandShowAsPercentOfColumnParent              12139
#define plCommandShowAsPercentOfGrandTotal                12140
#define plCommandFormatAlignLeft                          12141
#define plCommandFormatAlignCenter                        12142
#define plCommandFormatAlignRight                         12143
#define plCommandFormatAlignAutomatic                     12158
#define plCommandFormatName                               12144
#define plCommandFormatSize                               12145
#define plCommandFormatForeColor                          12147
#define plCommandFormatBackColor                          12148
#define plCommandShowAllPropertiesInReport                12149
#define plCommandHideAllPropertiesInReport                12150
#define plCommandShowAllPropertiesInScreenTip             12151
#define plCommandHideAllPropertiesInScreenTip             12152
#define plCommandProfile                                  12153
#define plCommandGroupMembers                             12155
#define plCommandUngroupMembers                           12156
#define plCommandCut                                      12157
