
*** Constant Group: WshExecStatus
#define WshRunning                                        0
#define WshFinished                                       1
#define WshFailed                                         2

*** Constant Group: __MIDL___MIDL_itf_iwshom_0111_0001
#define WshRunning                                        0
#define WshFinished                                       1
#define WshFailed                                         2

*** Constant Group: CompareMethod
#define BinaryCompare                                     0
#define TextCompare                                       1
#define DatabaseCompare                                   2

*** Constant Group: IOMode
#define ForReading                                        1
#define ForWriting                                        2
#define ForAppending                                      8

*** Constant Group: Tristate
#define TristateTrue                                      -1
#define TristateFalse                                     0
#define TristateUseDefault                                -2
#define TristateMixed                                     -2

*** Constant Group: FileAttribute
#define Normal                                            0
#define ReadOnly                                          1
#define Hidden                                            2
#define System                                            4
#define Volume                                            8
#define Directory                                         16
#define Archive                                           32
#define Alias                                             1024
#define Compressed                                        2048

*** Constant Group: __MIDL___MIDL_itf_iwshom_0000_0001
#define Normal                                            0
#define ReadOnly                                          1
#define Hidden                                            2
#define System                                            4
#define Volume                                            8
#define Directory                                         16
#define Archive                                           32
#define Alias                                             1024
#define Compressed                                        2048

*** Constant Group: DriveTypeConst
#define UnknownType                                       0
#define Removable                                         1
#define Fixed                                             2
#define Remote                                            3
#define CDRom                                             4
#define RamDisk                                           5

*** Constant Group: __MIDL___MIDL_itf_iwshom_0000_0002
#define UnknownType                                       0
#define Removable                                         1
#define Fixed                                             2
#define Remote                                            3
#define CDRom                                             4
#define RamDisk                                           5

*** Constant Group: SpecialFolderConst
#define WindowsFolder                                     0
#define SystemFolder                                      1
#define TemporaryFolder                                   2

*** Constant Group: __MIDL___MIDL_itf_iwshom_0000_0003
#define WindowsFolder                                     0
#define SystemFolder                                      1
#define TemporaryFolder                                   2

*** Constant Group: StandardStreamTypes
#define StdIn                                             0
#define StdOut                                            1
#define StdErr                                            2

*** Constant Group: __MIDL___MIDL_itf_iwshom_0000_0004
#define StdIn                                             0
#define StdOut                                            1
#define StdErr                                            2

*** Constant Group: WshWindowStyle
#define WshHide                                           0
#define WshNormalFocus                                    1
#define WshMinimizedFocus                                 2
#define WshMaximizedFocus                                 3
#define WshNormalNoFocus                                  4
#define WshMinimizedNoFocus                               6

*** Constant Group: __MIDL___MIDL_itf_iwshom_0102_0001
#define WshHide                                           0
#define WshNormalFocus                                    1
#define WshMinimizedFocus                                 2
#define WshMaximizedFocus                                 3
#define WshNormalNoFocus                                  4
#define WshMinimizedNoFocus                               6
